# Generated by Django 4.1.7 on 2023-06-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_delete_shippingaddress_alter_cartitem_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
