# Generated by Django 4.1.7 on 2023-06-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_cart_delete_cartitem'),
    ]

    operations = [
    ]
