# Generated by Django 4.1.7 on 2023-06-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20230608_1850'),
    ]

    operations = [
    ]
