# Generated by Django 4.1.7 on 2023-06-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20230608_1854'),
    ]

    operations = [
    ]
