# Generated by Django 4.1.7 on 2023-03-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvariant_sizevariant_product_colorvariant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariant',
            name='colorname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='sizename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
