# Generated by Django 4.1.7 on 2023-06-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_colorvariant_colorname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colorvariant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizevariant',
        ),
        migrations.DeleteModel(
            name='ColorVariant',
        ),
        migrations.DeleteModel(
            name='SizeVariant',
        ),
    ]
